name: Update Language Statistics

on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC (5pm Seattle)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: garciaErick/Github-Language-Stats@main
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard"
          output_path: "github-stats"
          exclude_repos: "tsunderelkasten,tsunderelkasten-pipboy,ci-skeleton-3,Sails.js-template,quartz-tsunderick-themes,blog.tsunderick.space,dotfiles,7th-heaven.tsunderick.space,digitalgarden,garciaErick.github.io,advanced-japanese-a,blog,family.tsunderick.space,tsunderick.space"
          extra_repos: "Ashfall-Software/brews-n-battles"
          exclude_languages: "HTML,CSS,SCSS,PowerShell,Ruby,Makefile,PHP,GLSL,GAP"
          dark_mode: "true"
          use_loc: "true"
